# Pt 1. Intro Neuron Code

In [12]:
import numpy as np
import sys
import matplotlib

print("python:", sys.version)
print("numpy:",np.__version__)
print("matplotlib:", matplotlib.__version__)

python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
numpy: 1.18.1
matplotlib: 3.1.3


In [13]:
x=[1,2,3]
np.mean(x)

2.0

In [18]:
inputs = [1.2, 4.6, 5.8]
weights = [3.1, 2.1, 4.5]
bias = 3
output = inputs[0]* weights [0] + inputs[1]* weights [1] +inputs[2]* weights [2] + bias
print (output)

42.48


# Pt 2. Coding a Layer


In [2]:
inputs = [1.2, 4.6, 5.8, 2.5]

weights1 = [3.1, 2.1, 4.5, 1.4]
weights2 = [0.6, -2.1, 4.4, 1.7]
weights3 = [3.5, 7.1, 8.5, -1.4]

bias1 = 0.6
bias2 = 6 
bias3 = 8.5 


output = [inputs[0]* weights1[0] + 
          inputs[1]* weights1[1] +
          inputs[2]* weights1[2] + 
          inputs[3]* weights1[3] +  bias1,
              
          inputs[0]* weights2[0] + 
          inputs[1]* weights2[1] +
          inputs[2]* weights2[2] + 
          inputs[3]* weights2[3] + bias2,
          
          inputs[0]* weights3[0] + 
          inputs[1]* weights3[1] +
          inputs[2]* weights3[2] + 
          inputs[3]* weights3[3] + bias3]

print (output)

[43.58, 26.83, 91.16]


The way you would change an output is to change the  weights and the  biases. 

The inputs cannot be  changed because they come from the actual input data OR they are part of outputs  which feed into an input.

Each input value has 3 unique sets of weights as these are the networks which feed into the input.


# The Dot Product

In [23]:
inputs = [1.2, 4.6, 5.8, 2.5]

weights = [[3.1, 2.1, 4.5, 1.4],
           [0.6, -2.1, 4.4, 1.7],
           [3.5, 7.1, 8.5, -1.4]]

biases = [0.6, 6, 8.5]

layer_outputs = []
for neuron_weight,neuron_bias in zip(weights,biases):
    neuron_output = 0 
    for n_input,weight in zip (inputs,neuron_weight):
        neuron_output += n_input*weight 
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[43.58, 26.83, 91.16]


In [13]:
for neuron_weight,neuron_bias in zip(weights,biases):
    print(neuron_weight,neuron_bias)

[3.1, 2.1, 4.5, 1.4] 0.6
[0.6, -2.1, 4.4, 1.7] 6
[3.5, 7.1, 8.5, -1.0] 8.5


In [6]:
a =[1,2,3]
b = [3,4,5]
c = zip(a,b)

In [7]:
for i in c:
    print(i)

(1, 3)
(2, 4)
(3, 5)


zip function is combining two lists, in this case the weights (a) to the bias (b)

weights and biases are values that will impact neuron output. 

In [8]:
some_value =  4
weight = 3.6
bias = 0.9

print (some_value*weight)
print (some_value+bias)

14.4
4.9


weight is chamging the magnitude and bias is ofsetting the weight which meaans that bias is the intercept in the equation y= mx+ c (line) 

shaape is how many elements are in each dimension of an array and how many dimensions there are. i.e. in 1 dimension there is one list (array in numpy and a vector in maths).

In 2 dimensions, there is a list of lists, and in numpy this is called a matrix ( a rectangular array). Arrarys have to be homologous which means at each dimension they need to have the same dimension.


A tensor is an object that can be represented as an array, so in deep learning tensors will be used as an array.
What are we trying to do?

inputs x weights + bias (vector)

--> you do this via  the  dot product 

the dot product of two vectors results in a scalar value (one value i.e. 20) 

In [20]:
"""For single neuron"""

inputs = [1.2, 4.6, 5.8, 2.5]
weights = [3.1, 2.1, 4.5, 1.4]
bias = 2

output = np.dot(weights,inputs)+bias
print(output)
           

44.98


In [27]:
"""For a layer of neurons"""
inputs = [1.2, 4.6, 5.8, 2.5]

weights = [[3.1, 2.1, 4.5, 1.4],
           [0.6, -2.1, 4.4, 1.7],
           [3.5, 7.1, 8.5, -1.4]]

biases = [0.6, 6, 8.5]

output = np.dot(weights,inputs)+biases
print(output)

[43.58 26.83 91.16]


weight isnt a vector its a matrix containing vectors. inputs is a vector which does not change the dot product but weights are not.

# Batches, Layer, and Objects 

Using batches for parallel computing with GPU is better than CPU.
Batches help with generalisation.

You can set the network with a larger sample size--> that's why you use a batch so you have a generalisation of the data and not just one set of inputs. This improves the line of best fit and is easier for  neuron to fit the sample size when fed in batches.

But if you input all the bacthes at once then the neural network will try to pick up EVERY standard deviation... so you need to introduce the batches gradually i.e. 32 (most common batch size), 64, 128.




In [1]:
inputs = [[1.2, 4.6, 5.8, 2.5],
          [4.6, 7, 8.1, -1.2], 
          [6, 7, -2, 8]]

weights = [[3.1, 2.1, 4.5, 1.4],
           [0.6, -2.1, 4.4, 1.7],
           [3.5, 7.1, 8.5, -1.4]]

biases = [0.6, 6, 8.5]

The dot product of matrix is multiplying each element in the row vector of first matrix with corresponding element in the vector column of the second matrix and then adding them up to get one single dot product of every column vector.


The number of columns and rows in both weights and inputs needs to be the same. 

If shape is unqual, you need to transpose the inputs to from horizontal to vertical (or vice versa).



In [5]:
inputs = [[1.2, 4.6, 5.8, 2.5],
          [4.6, 7, 8.1, -1.2], 
          [6, 7, -2, 8]]

weights = [[3.1, 2.1, 4.5, 1.4],
           [0.6, -2.1, 4.4, 1.7],
           [3.5, 7.1, 8.5, -1.4]]

biases = [0.6, 6, 8.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 43.58  26.83  91.16]
 [ 64.33  27.66 144.83]
 [ 36.1   -0.3   51.  ]]


In [9]:

weights2 = [[3.4, 2.6, 4.1],
           [-0.5, 2.7, 4.6],
           [-3.5, 5.1, 8.5,]]

biases2 = [0.4, 8, 1.7]


layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)


[[ 592.086  477.987  760.863]
 [ 884.841  716.735 1148.666]
 [ 331.46   223.74   307.32 ]]


In [47]:
# X is the standard input for machine learning. 

np.random.seed(0)

X = [[3.4, 2.6, 4.1],
    [-0.5, 2.7, 4.6],
    [-3.5, 5.1, 8.5,]]

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases= np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(3,5)
layer2 = Layer_Dense (5,2)

layer1.forward(X)
print (layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

    
print(0.10*np.random.randn(4,3))
    
""" we usually initiliase weights between -1 and +1 and biases as 0. 
If inputs x weights is not big enough to fire then you have dead network issue so you have to sort something 
with the biases as a non 0 number"""

""""""


    
    

[[ 0.40474341  0.97932858  0.60544351  0.78495354  0.92370925]
 [-0.2858076   0.90548183  0.26027401 -0.08394324  0.22166078]
 [-0.993393    1.58062255  0.2271316  -0.73353047 -0.06695631]]
[[-0.0755456   0.21407593]
 [-0.07228084 -0.03774669]
 [-0.12794962 -0.23552952]]
[[-0.14543657  0.00457585 -0.01871839]
 [ 0.15327792  0.14693588  0.01549474]
 [ 0.03781625 -0.08877857 -0.19807965]
 [-0.03479121  0.0156349   0.12302907]]


''

In [36]:
np.random.randn(1,5)

array([[ 0.44386323,  0.33367433,  1.49407907, -0.20515826,  0.3130677 ]])

In [37]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])